# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set Env Vars on Heroku Project
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "rello-backend" #Must be unique in Heroku
        heroku_email: "dipta.biswas231998@gmail.com"
      env:
          HD_FRONT_END_URL: https://trello-clone-76971.web.app/
          HD_JWT_KEY: ${{ secrets.JWT_KEY }}
          HD_MONGO_URL: ${{ secrets.MONGO_URL }}
          HD_SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          HD_SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          HD_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          HD_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          HD_CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          HD_CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          HD_CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          HD_CLOUDINARY_DEFAULT_FOLDER: ${{ secrets.CLOUDINARY_DEFAULT_FOLDER }}
          HD_CLOUDINARY_PRESET: ${{ secrets.CLOUDINARY_PRESET }}
          HD_APP_NAME: Rello
